### PR TITLE
Release modelix-24.1

### PR DESCRIPTION
**Pull request by mhuster23**

### CODE REVIEW

**Comment by mhuster23** [comment]
This is still missing the actual versions for the release.

**Review by benedekh — DISMISSED** [review]

**Comment by mhuster23** [comment]
Seems like after the restructuring the test doesn't work properly anymore. Investigating...

**Comment by mhuster23** [comment]
I partially reverted the restructuring and extended the old test.

**Review by languitar — APPROVED** [review]
I can't spot any mistakes.

**Pull request merged**
